Tour Packages and Bookings/Tour Packages and Bookings/Controllers/BookingsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Tour_Packages_and_Bookings.Models;

namespace Tour_Packages_and_Bookings.Controllers
{
    public class BookingsController : Controller
    {
        private readonly TourDbContext db;
        public BookingsController(TourDbContext db) 
        {
            this.db = db;
        }
        public IActionResult Index()
        {
            return View(); 
        }
        public IActionResult Create(int id)
        {
            ViewBag.TourPackageId = id;
            return View();
        }

        [HttpPost]
        public IActionResult Create(Booking model) 
        {
            if (ModelState.IsValid)
            {
                db.Database.ExecuteSqlInterpolated($"EXEC InsertBooking {model.TravelerName},{model.PhoneNumber},{model.NumberOfTravelers}, {model.BookingDate}, {model.BookingStatus} , {model.TourPackageId}");
                return RedirectToAction("Index", "TourPackages");
            }
            ViewBag.TourPackages = db.TourPackages.ToList();
            return View(model);
        }
        public IActionResult Edit(int id)
        {
            var data = db.Bookings.FirstOrDefault(x => x.BookingId == id);
            if (data == null) { return NotFound(); }
            ViewBag.TourPackages = db.TourPackages.ToList();
            return View(data);
        }

        [HttpPost]
        public IActionResult Edit(Booking model)
        {
            if (ModelState.IsValid)
            {
                db.Database.ExecuteSqlInterpolated($"EXEC UpdateBooking {model.BookingId}, {model.TravelerName},{model.PhoneNumber},{model.NumberOfTravelers}, {model.BookingDate}, {model.BookingStatus} , {model.TourPackageId}");
                return RedirectToAction("Index", "TourPackages");
            }
            ViewBag.TourPackages = db.TourPackages.ToList();
            return View(model);
        }
        [HttpPost]
        public IActionResult Delete(int id)
        {
            db.Database.ExecuteSqlInterpolated($"EXEC DeleteBooking {id}");
            return Json(new { success = true, id });
        }
    }
}

Tour Packages and Bookings/Tour Packages and Bookings/Views/Bookings/Create.cshtml
@model Booking
@{
    ViewData["Title"] = "Create";
}

<div class="container">
    <div class="row justify-content-center" style="margin-top: 40px;">
        <div class="col-12">
            <form asp-action="Create" asp-controller="Bookings" method="post" class="needs-validation">
                <h3 class="d-flex justify-content-center mb-3"><u>Add new Booking</u></h3>
                <input type="hidden" asp-for="TourPackageId" value="@ViewBag.TourPackageId" />

                <div class="form-group row mb-1 offset-2">
                    <label class="col-form-label col-2" asp-for="TravelerName"></label>
                    <div class="col-6">
                        <input asp-for="TravelerName" class="form-control" />
                        <span asp-validation-for="TravelerName" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row mb-1 offset-2">
                    <label class="col-form-label col-2" asp-for="PhoneNumber"></label>
                    <div class="col-6">
                        <input asp-for="PhoneNumber" class="form-control" />
                        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row mb-1 offset-2">
                    <label class="col-form-label col-2" asp-for="NumberOfTravelers"></label>
                    <div class="col-6">
                        <input asp-for="NumberOfTravelers" class="form-control" />
                        <span asp-validation-for="NumberOfTravelers" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row mb-1 offset-2">
                    <label class="col-form-label col-2" asp-for="BookingDate"></label>
                    <div class="col-6">
                        <input type="date" asp-for="BookingDate" class="form-control" />
                        <span asp-validation-for="BookingDate" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row mb-1 offset-2">
                    <label class="col-form-label col-2" asp-for="BookingStatus"></label>
                    <div class="col-6">
                        <input asp-for="BookingStatus" class="form-control" />
                        <span asp-validation-for="BookingStatus" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row mt-2 offset-2">
                    <div class="col-8">
                        <div class="d-flex justify-content-between">
                            <a asp-action="Index" asp-controller="TourPackages" class="btn btn-secondary"><i class="bi bi-arrow-return-left"> Back to index</i></a>
                            <button type="submit" class="btn btn-primary"><i class="bi bi-save"> Save</i></button>
                        </div>
                   </div>
                </div>
            </form>
        </div>
    </div>
</div>
@section scripts
    {
    <script src="~/libs/jquery/jquery.js"></script>
    <script src="~/libs/validate/jquery.validate.js"></script>
    <script src="~/libs/validate/jquery.validate.unobtrusive.js"></script>
}

Tour Packages and Bookings/Tour Packages and Bookings/Views/Bookings/Edit.cshtml
@model Booking
@{
    ViewData["Title"] = "Edit";
}
<div class="container">
    <div class="row justify-content-center" style="margin-top: 40px;">
        <div class="col-12 col-md-8">
            <form asp-action="Edit" asp-controller="Bookings" method="post" class="needs-validation">
                <h3 class="text-center mb-4">Edit Booking</h3>
                <input type="hidden" asp-for="BookingId" />
                <input type="hidden" asp-for="TourPackageId" />

                <div class="form-group row mb-3">
                    <label class="col-form-label col-2" asp-for="TravelerName"></label>
                    <div class="col-10">
                        <input asp-for="TravelerName" class="form-control" />
                        <span asp-validation-for="TravelerName" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row mb-3">
                    <label class="col-form-label col-2" asp-for="PhoneNumber"></label>
                    <div class="col-10">
                        <input asp-for="PhoneNumber" class="form-control" />
                        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row mb-3">
                    <label class="col-form-label col-2" asp-for="NumberOfTravelers"></label>
                    <div class="col-10">
                        <input asp-for="NumberOfTravelers" class="form-control" />
                        <span asp-validation-for="NumberOfTravelers" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row mb-3">
                    <label class="col-form-label col-2" asp-for="BookingDate"></label>
                    <div class="col-10">
                        <input type="date" asp-for="BookingDate" class="form-control" />
                        <span asp-validation-for="BookingDate" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row mb-3">
                    <label class="col-form-label col-2" asp-for="BookingStatus"></label>
                    <div class="col-10">
                        <input asp-for="BookingStatus" class="form-control" />
                        <span asp-validation-for="BookingStatus" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row mb-4">
                    <div class="col-10 offset-2">
                        <div class="d-flex justify-content-between">
                            <a asp-action="Index" asp-controller="TourPackages" class="btn btn-secondary"><i class="bi bi-arrow-return-left"></i> Back to index</a>
                            <button type="submit" class="btn btn-primary"><i class="bi bi-save"></i> Save</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@section scripts
    {
    <script src="~/libs/jquery/jquery.js"></script>
    <script src="~/libs/jquery-validate/jquery.validate.js"></script>
    <script src="~/libs/jquery-validate/jquery.validate.unobtrusive.js"></script>
}